DROP TABLE IF EXISTS POST_TAGS;
DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    no BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL, -- CLOB is suitable for 10MB+ in H2
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    views INT DEFAULT 0
);

CREATE TABLE POST_TAGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_NO BIGINT NOT NULL,
    TAG_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (POST_NO) REFERENCES posts(no) ON DELETE CASCADE
);
